import { HeaderChat } from '@/components/header';
import Head from 'next/head'
import React, { useState } from 'react';
import { login, writeUserData } from '@/utils/helper';
import { useRouter } from 'next/router';

export default function AddUser() {
  const router = useRouter()

  const submitUser = async () => {
    if(username && password) {
      const auth = await login(username, password);
      if(auth) {
        router.push(`/history?username=${username}`);
      }
    }
  }

  const [email, setEmail] = useState<string>('');
  const [username, setUsername] = useState<string>('');
  const [password, setPassword] = useState<string>('');

  return (
    <>
      <Head>
        <title>Add User</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
        <div style={{ display: 'flex', flexDirection: 'column', height: '100vh', width: '100vw', justifyContent: 'space-between', alignItems:'center'}}>
            <HeaderChat title={"Add User"} />
            <div style={{ display: 'flex', flex: 1, alignItems: 'center', width: '75%' }}>
              <div style={{ display: 'flex', alignItems: 'center', height: '50%', flex: 1, border: '1px #ddd solid', borderRadius: 4}}>
                <div style={{ display: 'flex', flex: 1, flexDirection: 'column', gap: '10px', alignItems: 'center'}}>
                <div style={{ fontSize: 30, }}>
                  Sign in
                </div>
                <label>
                  Employee id
                </label>
                <input 
                    type="text" 
                    name="username" 
                    value={username} 
                    onChange={a => setUsername(a?.target?.value || "")} 
                    style={{ height: '30px', width: '50%', fontSize: 18, textIndent: 10 }} 
                />

                <label>
                  password
                </label>
                <input 
                    type="password" 
                    name="password" 
                    value={password} 
                    onChange={a => setPassword(a?.target?.value || "")} 
                    style={{ height: '30px', width: '50%', fontSize: 18, textIndent: 10 }} 
                />
                <input
                  type="button"
                  name="submit"
                  value="submit"
                  style={{ height: '30px', width: '50%'}}
                  onClick={submitUser}
                />
                </div>  
              </div>
            </div>
            {/* <Keyboard /> */}
        </div>
    </>
  )
}
